name: Master CICD Pipeline

on:
  push:
    branches: master

jobs:

  build:
    name: Continuous Integration of the endpoint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Display something useless
      run: |
        echo "Hello World automated from the master pipeline !"

    - name: Build docker image
      run: |
        docker build . -t ghcr.io/stefvra/dockercicd/project-api:latest

    - name: Test the Docker image built before with
      run: |
        docker run \
        --entrypoint=/bin/bash \
        project-api:latest \
        ./script/test

    - name: Login and push the Docker image to Github Packages
      run: |
        docker login https://ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
        docker push ghcr.io/stefvra/dockercicd/project-api:latest